### ISSUE TITLE
How to integrate SPDM-emu to openbmc?

### ISSUE THREAD

**Issue by savatagecriss** [DMTF/spdm-emu#10]
Hi 
I appreciated the spdm-emu project, but we want to integrate spdm-emu to openbmc project to do some evaluation on qemu, 

So could you share any hint how to write a recipe to integrate spdm-emu into openbmc(maybe romulus or ast2600evb)?
And could you share how to build spdm-emu for static linking based on ARM_GCC toolchain?

Thanks
John

**Comment by jyao1** [comment]
sorry, I am not familiar with openbmc.

Can you introduce how to build openbmc?

**Comment by savatagecriss** [comment]
Hi jyao
Thanks for your reply, I think my question is not clear, and my issue has been solved.

I want to run spdm-requester-emu and spdm-responder-emu on openbmc+qemu, but I got "segment fault" issue when I run responder-emu, and after troubleshooting, I found that's because there are no certificate relative files, after put some files in RSA3072 and ecp384 folders to my openbmc+qemu, both emu can run on my openbmc+qemu, I can see the SPDM handshake messages.

Because I saw the message **_"Support to be included in OpenBMC. It is in planning"_** on libspdm github project, so I thought this library is ready for openbmc, and I am not familiar with openbmc too, so here are only my steps that I tried:
1. clone openbmc project
2. In openbmc folder, run "_**. setup romulus build**_" (it's a ast2500 project), then run _**"bitbake obmc-phosphor-image"**_.
3. After build success, use qemu to run the obmc-image
4. Try to put both emu and all keys relative files to openbmc-qemu, run them, then you should see all the SPDM handshake messages.

Regards,
John
