### ISSUE TITLE
spdm_responder_emu will hang when run using --trans NONE

### ISSUE THREAD

**Issue by lbbxsxlz** [DMTF/spdm-emu#105]
Version: [2.1.0](https://github.com/DMTF/spdm-emu/releases/tag/2.1.0)
commit c94124dfa97b9c1426baf0613c5117f5a5373e50

compile command:
cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=mbedtls ..

responder:
./spdm_responder_emu --trans NONE

requester:
./spdm_requester_emu --trans NONE

responder log:
.....
Platform port Transmit command: 00 00 00 01
Platform port Transmit transport_type: 00 00 00 00
Platform port Transmit size: 00 00 00 34
Platform port Transmit buffer:
    12 65 00 00 71 b3 36 fa 7e b9 35 ac 48 78 15 09 58 0f 24 77 4c 34 22 ca fb 1c 5d 4a 08 72 fe e6 84 3b ca 5c 7e 80 dc aa c5 e5 04 53 8c c5 78 c6 0e 16 6e a3
Platform port Receive command: 00 00 00 01
Platform port Receive transport_type: 00 00 00 00
Platform port Receive size: 00 00 00 1c
Platform port Receive buffer:
    ff ff ff ff 16 00 d3 b7 4e bb 40 38 25 f1 ba 3e 50 40 a5 2b 6d 62 73 2e 61 cb 87 c9
SpdmReceiveRequest[.] ...
SpdmReceiveRequest[0] (0x1c):
0000: ff ff ff ff 16 00 d3 b7 4e bb 40 38 25 f1 ba 3e 50 40 a5 2b 6d 62 73 2e 61 cb 87 c9
SpdmSendResponse[0] ...
LIBSPDM_ASSERT: /home/binbin/workspace/SPDM/spdm-emu-2.1.0/libspdm/library/spdm_responder_lib/libspdm_rsp_receive_send.c(87): request_code != 0xFF

requester log:
....
libspdm_start_session - libspdm_send_receive_finish - (nil)
libspdm_send_spdm_request[ffffffff] (0x4):
0000: 12 e8 00 00
Platform port Transmit command: 00 00 00 01
Platform port Transmit transport_type: 00 00 00 00
Platform port Transmit size: 00 00 00 1c
Platform port Transmit buffer:
    ff ff ff ff 16 00 d3 b7 4e bb 40 38 25 f1 ba 3e 50 40 a5 2b 6d 62 73 2e 61 cb 87 c9

**Comment by jyao1** [comment]
@jklmnn, would you please take a look?

**Comment by lbbxsxlz** [comment]
The solution request #116  is merged!
