### ISSUE TITLE
The parameter of malloc function may be negative

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/spdm-emu#121]
https://github.com/DMTF/spdm-emu/blob/aef708d2016a17722ff9eddb7f312fb5ac8e4f7e/spdm_emu/spdm_emu_common/support.c#L61-L65

When an error occurs in the ftell function, it will return a negative value.
If the parameter of malloc function is negative, the memory request will fail.

**Comment by liuw1** [comment]
I will take it
