### ISSUE TITLE
status may not be initialized

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/spdm-emu#122]
https://github.com/DMTF/spdm-emu/blob/aef708d2016a17722ff9eddb7f312fb5ac8e4f7e/spdm_emu/spdm_responder_emu/spdm_responder_session.c#L39-L59

Line 39 defines status, but when line 41 and line 48 if are false, status is not initialized and is used in line 55.

**Comment by liuw1** [comment]
I will take it
