### ISSUE TITLE
a negative parameter being interpreted as unsigned.

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/spdm-emu#123]
1. line 318 `libspdm_read_responder_root_public_certificate` function may change the value of `data_size` to zero.
line 324 `data_size - sizeof(spdm_cert_chain_t) - hash_size` may be negative value.

https://github.com/DMTF/spdm-emu/blob/aef708d2016a17722ff9eddb7f312fb5ac8e4f7e/spdm_emu/spdm_requester_emu/spdm_requester_spdm.c#L318-L325
if line 49 return false, `data_size` will be zero.
bool libspdm_read_responder_root_public_certificate( )
https://github.com/DMTF/libspdm/blob/5cf400da304b6682920158c2e583a2f9242027ec/os_stub/spdm_device_secret_lib_sample/cert.c#L39-L50
![image](https://user-images.githubusercontent.com/99862485/182312073-0bcac9f5-48ee-4f5c-9e5b-074746213575.png)
2. `data1_size` may be zero. same issue.
https://github.com/DMTF/spdm-emu/blob/aef708d2016a17722ff9eddb7f312fb5ac8e4f7e/spdm_emu/spdm_requester_emu/spdm_requester_spdm.c#L339-L347

**Comment by liuw1** [comment]
I will take it
