### ISSUE TITLE
Resource acquired to 'client_socket' may be lost

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/spdm-emu#130]
1. Resource acquired to `client_socket` at line 50 may be lost at line 59 `return false;`. I'm not 100% sure whether it is an issue. 
https://github.com/DMTF/spdm-emu/blob/40dc3da69ab8273c2250ea56ac32b0b5713cb445/spdm_emu/spdm_requester_emu/spdm_requester_emu.c#L50-L60
2. Three similar cases:
https://github.com/DMTF/spdm-emu/blob/40dc3da69ab8273c2250ea56ac32b0b5713cb445/spdm_emu/spdm_responder_emu/spdm_responder_emu.c#L35-L45
https://github.com/DMTF/spdm-emu/blob/40dc3da69ab8273c2250ea56ac32b0b5713cb445/spdm_emu/spdm_device_attester_sample/spdm_device_attester_sample.c#L40-L50
https://github.com/DMTF/spdm-emu/blob/40dc3da69ab8273c2250ea56ac32b0b5713cb445/spdm_emu/spdm_device_validator_sample/spdm_device_validator_sample.c#L40-L50

**Comment by Wenxing-hou** [comment]
I don't think there need add `closesocket(client_socket);`, because the `Create socket Failed` in here. This issue may be closed.

**Comment by Wenxing-hou** [comment]
From [windows doc: socket funciotn](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-socket), we can find `closesocket` was not used when `socket` return `INVALID_SOCKET`.

```
    sock = socket(iFamily, iType, iProtocol);
    if (sock == INVALID_SOCKET) 
        wprintf(L"socket function failed with error = %d\n", WSAGetLastError() );
    else {
        wprintf(L"socket function succeeded\n");

        // Close the socket to release the resources associated
        // Normally an application calls shutdown() before closesocket 
        //   to  disables sends or receives on a socket first
        // This isn't needed in this simple sample
        iResult = closesocket(sock);
        if (iResult == SOCKET_ERROR) {
            wprintf(L"closesocket failed with error = %d\n", WSAGetLastError() );
            WSACleanup();
            return 1;
        }    
    }

    WSACleanup();

    return 0;
}
```

And from [windows doc: WSACleanup function](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsacleanup), we can find 
_An application or DLL is required to perform a successful [WSAStartup](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) call before it can use Windows Sockets services. When it has completed the use of Windows Sockets, the application or DLL must call WSACleanup to deregister itself from a Windows Sockets implementation and allow the implementation to free any resources allocated on behalf of the application or DLL._

I have submitted the PR to fix it.
