### ISSUE TITLE
'VerifyCertificateChainData - FAIL' when running spdm_responder_emu and spdm_requester_emu without any parameter

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/spdm-emu#14]
Test at the commit 2c4ada8

1. Open **one** command prompt to run
C:\spdm-emu1011\build\bin>spdm_responder_emu.exe > responder.log

2. Open **another** command prompt to run
C:\spdm-emu1011\build\bin>spdm_requester_emu.exe > requester.log

3. check the 'requester.log', there is a fail at line 59 as following:
!!! VerifyCertificateChainData - FAIL (cert chain verify failed)!!!

4. Please refer to the attached 'requester.log'.
[requester.log](https://github.com/DMTF/spdm-emu/files/7327000/requester.log)
.

**Comment by joliqi** [comment]
same fail again now

**Comment by yaohuixguo** [comment]
> @joliqi 

Verified on 14a8c2e5ff26c0addfafff02cfbfa5be1da31977

In Windows:
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug|Release -DCRYPTO=mbedtls|openssl ..
No same fail,

In Linux:
cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug|Release -DCRYPTO=mbedtls|openssl ..
No same fail,

What version do you use?

**Comment by joliqi** [comment]
@yaohuixguo 

I also use https://github.com/DMTF/spdm-emu/commit/14a8c2e5ff26c0addfafff02cfbfa5be1da31977

my os is fc35
`$ uname -a
Linux fedora 5.18.0-rc7 #1 SMP PREEMPT_DYNAMIC Wed May 17 17:50:00 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
`

build
`
mkdir build;
cd build;
cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl .. ;
make copy_sample_key;
make;
`

run
`
$ ./spdm_responder_emu --trans PCI_DOE > responder.log
`
[responder.log](https://github.com/DMTF/spdm-emu/files/9850054/responder.log)

`
$ ./spdm_requester_emu --trans PCI_DOE > requester.log
`
[requester.log](https://github.com/DMTF/spdm-emu/files/9850055/requester.log)


anything i miss?

**Comment by yaohuixguo** [comment]
@joliqi 

Maybe the OS is different.
my os is Ubuntu
`Linux test-Vostro-3902 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

You can verify it on Ubuntu, and I will verify it on fedora.

**Comment by joliqi** [comment]
@yaohuixguo 
it also passed in my ubuntu 22.04
