### ISSUE TITLE
spdm_get_measurements returning spdm_error (ErrCode=0x01)

### ISSUE THREAD

**Issue by m8jin** [DMTF/spdm-emu#162]
When running the default setting of the spdm emulator, it appears that spdm runs the SPDM_GET_MEASUREMENTS command for each certificate in the slot id (MeasOp=0x00 through MeasOp=0xfe). However, for the majority of the get_measurement operations, the responder returns the SPDM_ERROR message (i.e. lines 52, 54, 56).

> 41 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x00(TotalNum)) 
42 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x60) SPDM_MEASUREMENTS (TotalMeasIndex=0x07) 
43 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x01) 
44 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x60) SPDM_MEASUREMENTS (NumOfBlocks=0x1, MeasRecordLen=0x47) 
45 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x02) 
46 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x60) SPDM_MEASUREMENTS (NumOfBlocks=0x1, MeasRecordLen=0x47) 
47 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x03) 
48 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x60) SPDM_MEASUREMENTS (NumOfBlocks=0x1, MeasRecordLen=0x47) 
49 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x04) 
50 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x60) SPDM_MEASUREMENTS (NumOfBlocks=0x1, MeasRecordLen=0x47) 
51 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x05) 
52 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x7f) SPDM_ERROR (ErrCode=0x01, ErrData=0x00) 
53 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x06) 
54 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x7f) SPDM_ERROR (ErrCode=0x01, ErrData=0x00) 
55 (1664917952) MCTP(5) REQ->RSP SPDM(12, 0xe0) SPDM_GET_MEASUREMENTS (Attr=0x00(), MeasOp=0x07) 
56 (1664917952) MCTP(5) RSP->REQ SPDM(12, 0x7f) SPDM_ERROR (ErrCode=0x01, ErrData=0x00) 

I have a few concerns regarding this issue. What is ErrCode 0x01 and why is the responder returning the SPDM_ERROR message? Also, based on my understanding of the SPDM spec, the protocol should be able to retrieve a specific measurement in the slot id. Is there a command in the user tools to do this, and if not, is there a reason why the emulator retrieves all of the measurements?

**Comment by steven-bellock** [comment]
@m8jin This is expected behavior in one-by-one mode as the Requester doesn't know which measurement indices are valid. So it sweeps through all the indices, some of which may return an `ERROR` response. If you think it might be beneficial we could allow measurements from a single index, or a set of indices. If so, please file a feature request in this repository.

**Comment by steven-bellock** [comment]
Closing for now. @m8jin if you'd like to further refine this please file a new issue.
