### ISSUE TITLE
'bytes_received' in function 'receive_platform_data' needs to be clear

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/spdm-emu#163]
Passing expression `bytes_received` to `append_pcap_packet_data`, which uses it as an offset.
`bytes_received` is an uncertain value, which needs to be checked in advance.
https://github.com/DMTF/spdm-emu/blob/0bc64fb1520daaf3dbc66f4cbb9d8fc0694ec86b/spdm_emu/spdm_emu_common/command.c#L165-L171

**Comment by Xiaohanjlll** [comment]
I will check it.
