### ISSUE TITLE
"VER_ONLY" hits an assertion

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/spdm-emu#166]
> spdm_requester_emu --exe_conn "VER_ONLY" --meas_op "ALL" --pcap requester.pcap  --exe_session "PSK,MEAS" --cap "ENCRYPT,MAC,PSK,HBEAT"

hits
>LIBSPDM_ASSERT: C:\repo\steven-bellock\spdm-emu\spdm_emu\spdm_requester_emu\spdm_requester_spdm.c(329): data32 == LIBSPDM_CONNECTION_STATE_NEGOTIATED

**Comment by Xiaohanjlll** [comment]
I will check it.

**Comment by jyao1** [comment]
It seems the fix does not resolve the problem. It does not assert but it will fail and exit.

**Comment by jyao1** [comment]
It is fixed by https://github.com/DMTF/spdm-emu/pull/200


Test:
```
spdm_responder_emu.exe --exe_conn VER_ONLY --exe_session PSK,MEAS --ver 1.2 --hash SHA_256 --meas_hash SHA_256 --asym RSASSA_2048 --req_asym RSASSA_2048 --dhe FFDHE_2048 --aead AES_128_GCM
spdm_requester_emu.exe --exe_conn VER_ONLY --exe_session PSK,MEAS --ver 1.2 --hash SHA_256 --meas_hash SHA_256 --asym RSASSA_2048 --req_asym RSASSA_2048 --dhe FFDHE_2048 --aead AES_128_GCM
```
