### ISSUE TITLE
Build errors with CLANG

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/spdm-emu#172]
[error_files.zip](https://github.com/DMTF/spdm-emu/files/9917737/error_files.zip)
Verified on 5679c23d52565255db8a7d34dc07ef46624150de
Ubuntu 20.04.2 LTS 

Build errors with CLANG:
`cmake -DARCH=x64 -DTOOLCHAIN=CLANG -DTARGET=Debug -DCRYPTO=mbedtls|openssl ..`

`/usr/bin/ld: ../../lib/libmemlib.a: error adding symbols: archive has no index; run ranlib to add one`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[2]: *** [spdm_emu/spdm_requester_emu/CMakeFiles/spdm_requester_emu.dir/build.make:287: bin/spdm_requester_emu] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:1844: spdm_emu/spdm_requester_emu/CMakeFiles/spdm_requester_emu.dir/all] Error 2`
`make: *** [Makefile:130: all] Error 2`

**Comment by Xiaohanjlll** [comment]
I will check it.
