### ISSUE TITLE
Build instructions do not work

### ISSUE THREAD

**Issue by tmarkey64** [DMTF/spdm-emu#213]
The readme build instructions for spdm-emu state to cd to spdm_emu and create build directory there.  However, there is no CMakeList.txt in spdm_emu, so I get the following error:

~/spdm-emu2/spdm_emu/build
$ cmake -Wno-deprecated -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl --log-level=VERBOSE ..
CMake Error: The source directory "/spdm-emu2/spdm_emu" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by steven-bellock** [comment]
In your case it would (probably) be `~/spdm-emu2/build`.

**Comment by steven-bellock** [comment]
@tmarkey64 Did that resolve your issue?

**Comment by tmarkey64** [comment]
@steven-bellock, yes I can build.  The spdm-emu/README.me states for building to cd spdm_emu/build, so this caused some confusion.
