### ISSUE TITLE
Question: uncrustify code formatting

### ISSUE THREAD

**Issue by ZhibinLiIntel** [DMTF/spdm-emu#215]
Hi guys. I noticed there is uncrustify code format support in this repo and libspdm. Even so I found that some of the files were not formatted correctly. For example `include/library/cxl_ide_km_common_lib.h` and `spdm_emu/spdm_emu_common/nv_storage.h`.

This is a trivial issue but I just wonder if there's a way to enforce this formatting against every file committed from spdm-emu's perspective?

**Comment by jyao1** [comment]
I think the only way is to add to CI.

Would you please help to submit a patch on that?

**Comment by ZhibinLiIntel** [comment]
> I think the only way is to add to CI.
> 
> Would you please help to submit a patch on that?

I'm not familiar with CI on github but yes, I will see what I can do later.
