### ISSUE TITLE
Checking for heartbeat interval while testing end_session_ack with validator (test 16)

### ISSUE THREAD

**Issue by PavelPu123** [DMTF/spdm-emu#224]
Hello
I'm not sure I understand the logic of checking the heartbeat interval in spdm_test_case_end_session_ack_setup_session (line 164):

if (test_buffer->heartbeat_period == 0)

This check affects the specific test since it's not a requirement to setup the heartbeat interval in responder as part of this test.

Thanks in advance for your comments.

**Comment by steven-bellock** [comment]
@PavelPu123 Please file this in https://github.com/DMTF/SPDM-Responder-Validator/issues.

**Comment by PavelPu123** [comment]
Moved
