### ISSUE TITLE
Can spdm-emu compile in arm architecture(32bit)？

### ISSUE THREAD

**Issue by FangYuFan** [DMTF/spdm-emu#247]
Can spdm-emu compile in arm architecture(32bit)？

**Comment by jyao1** [comment]
I did not try.

spdm-emu depends on std.

If the ARM 32bit supports std, such as Linux OS, then maybe you can run it.

**Comment by FangYuFan** [comment]
> I did not try.
> 
> spdm-emu depends on std.
> 
> If the ARM 32bit supports std, such as Linux OS, then maybe you can run it.



> 

It can be compiled in ARM architecture.
One more question, it seems that the project cannot be compiled with GCC on Windows, since the source code uses the _MSC_VER macro, right?

**Comment by steven-bellock** [comment]
libspdm supports MinGW. Not sure if spdm-emu does.
