### ISSUE TITLE
Why requester need to get_digest twice and get_certificate after challenge?

### ISSUE THREAD

**Issue by owen126315** [DMTF/spdm-emu#256]
I through the requester already get the certificate chain and its hash, and corresponding signature after reciving challenge_auth.
Suppose the requester can verify the responder at this stage, but why the example code still get_digest and get_certificate again?

https://github.com/DMTF/spdm-emu/blob/85e52e37014e653e2b917ddac9fb1121a26c3267/spdm_emu/spdm_requester_emu/spdm_requester_authentication.c#L93-L118

**Comment by jyao1** [comment]
This is to ensure we can get that twice, because we had lots of debate on how to get digest twice.
