### ISSUE TITLE
spdm-emu test fails with '--priv_key_mode RAW' option

### ISSUE THREAD

**Issue by DavidPu** [DMTF/spdm-emu#257]
It fails with following error at requester side:
`!!! verify_challenge_signature - FAIL !!!`

it is built with default configurations: 
`cmake -DARCH=x64 -DTARGET=Debug  -DTOOLCHAIN=GCC -DCRYPTO=mbedtls ..` 

executed as:
responder: ./spdm_responder_emu --priv_key_mode RAW
requester: ./spdm_requester_emu --priv_key_mode RAW

**Comment by jyao1** [comment]
root cause: https://github.com/DMTF/libspdm/issues/2106

**Comment by jyao1** [comment]
Fixed after libspdm sync.
