### ISSUE TITLE
CI/CD reports success when "test" fails

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/spdm-emu#265]
For example see https://github.com/DMTF/spdm-emu/actions/runs/5223706120/jobs/9430943017?pr=264#step:5:385

It looks like this is specific to Visual Studio.

**Comment by steven-bellock** [comment]
There's also
```
        run: |
          cd build/bin
          ./spdm_responder_emu &
          ./spdm_requester_emu
```
and I have no idea how it's running successfully in CI/CD, but it does.

**Comment by steven-bellock** [comment]
@jyao1 @Wenxing-hou how do these spdm-emu "tests" know when to end?

**Comment by xiaoyuxlu** [comment]
I suggest if spdm_emu_requester/responder fails, set the exit code to non-zero.
