### ISSUE TITLE
Where are the raw data located?

### ISSUE THREAD

**Issue by mehdiae** [DMTF/spdm-emu#270]
Hi,
I am trying to emulate a device and wanted to know where the measurements raw data are located. Our system returns raw sha256 and I used `./spdm_responder_emu --ver 1.0 --cap MEAS_NO_SIG --hash SHA_256 --meas_hash SHA_256` for emulating it. spdm_responder_emu returns "05 10 60 00 00 01 27 00 00 01 01 23 00 00 20 00 c8 be d0 af 54 73 e9 56 f3 8c 0d ef 7c 0b 50 47 ff 75 6a 6a 7e 66 6f 5f 3f b9 56 c5 c1 65 2b 1e 57 b5 22 48 95 3a 37 2e 0d e4 28 2f ef cf 1a 9a 17 b3 9e 5c dc 59 05 28 34 56 a0 4d 25 eb 4f 26 00 00" and I extracted "c8 be d0 af 54 73 e9 56 f3 8c 0d ef 7c 0b 50 47 ff 75 6a 6a 7e 66 6f 5f 3f b9 56 c5 c1 65 2b 1e" as the measurement. I want to know what is the raw data that this is calculated based on?

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/c70fc237601628c271e576bca823aec481a35b8a/os_stub/spdm_device_secret_lib_sample/lib.c#L942

**Comment by mehdiae** [comment]
Thanks for the direction. Basically, the raw data is the index repeated LIBSPDM_MEASUREMENT_RAW_DATA_SIZE times
