### ISSUE TITLE
why do not zero “data32” before use?

### ISSUE THREAD

**Issue by FangYuFan** [DMTF/spdm-emu#275]
https://github.com/DMTF/spdm-emu/blob/5dd34068a580e96e3dc64d10ab35289ad4e35828/spdm_emu/spdm_requester_emu/spdm_requester_spdm.c#L399C13-L399C13

In the code linked above, the libspdm_get_data() function shall only assign a value to the first byte in data32. If data32 is not zeroed in advance, an abnormal value may be obtained, causing the next line of assert to trigger

**Comment by jyao1** [comment]
libspdm_connection_state_t is enum type, which is 32bit. Why it only assign the first byte?

Do you run into some real issue? or you just think there might be issue?

**Comment by FangYuFan** [comment]
> libspdm_connection_state_t is enum type, which is 32bit. Why it only assign the first byte?
> 
> Do you run into some real issue? or you just think there might be issue?

**Comment by FangYuFan** [comment]
> libspdm_connection_state_t is enum type, which is 32bit. Why it only assign the first byte?
> 
> Do you run into some real issue? or you just think there might be issue?

It's a real issue. 
In some platforms, the compiler will optimize the size according to the value range in the enum. For example, in the arm platform, the armcc compiler will optimize the enum size below the range of 255 to 1 byte. 
Of course, we can add compilation parameters to force all enum sizes to be fixed at 32 bit, but this will increase some RAM consumption, which is not very friendly to the operating environment with small memory

**Comment by steven-bellock** [comment]
Can change it from `sizeof(data32)` to `sizeof(libspdm_data_type_t)`.

**Comment by jyao1** [comment]
C standard said: The expression that defines the value of an enumeration constant shall be an integer constant expression that has a value representable as an int.

I think this is the compiler should do.

**Comment by FangYuFan** [comment]
> 

Okay, I understand what you mean, but I think what Steven Bellock said above will make the code more stable. This is just a suggestion
