### ISSUE TITLE
question about scratch_buffer

### ISSUE THREAD

**Issue by FangYuFan** [DMTF/spdm-emu#276]
https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_responder_emu/spdm_responder_spdm.c#L191C60-L191C60
https://github.com/DMTF/libspdm/blob/51d96e9c8451fe101d32a2701d8f5735ba0c3f86/include/internal/libspdm_common_lib.h#L469C26-L469C26
Due to limited RAM size, if I do not support the ability to secure sessions and chunks, can I remove the scratch_buffer variable which in the libspdm_context_t?
or wolud you please explain the purpose of this variable.

**Comment by steven-bellock** [comment]
If an endpoint does not support encryption or chunking then libspdm should directly use the send / receive buffers to construct messages. I do not think it does that now, so that would be an enhancement to libspdm. Feel free to file an issue.

**Comment by FangYuFan** [comment]
> 

Get it. Thanks for your reply.
