### ISSUE TITLE
command  assert:  spdm_requester_emu.exe --trans MCTP --exe_conn DIGEST

### ISSUE THREAD

**Issue by YangYunLong1988** [DMTF/spdm-emu#280]
[response.log](https://github.com/DMTF/spdm-emu/files/12170705/response.log)
[resuest.log](https://github.com/DMTF/spdm-emu/files/12170707/resuest.log)

response cmd : spdm_responder_emu.exe
request cmd : spdm_requester_emu.exe --trans MCTP --exe_conn DIGEST

**spdm_requester_emu.exe** will hit an assert, May i know if this is expected ? or i do something stupid ?

**Comment by jyao1** [comment]
The reason is that: you only override `--exe_conn`, but not `--exe_session`.
Since there is no `CERT`, key_exchange will fail because the certificate is not retrieved.

There could be multiple mays to fix it.

@YangYunLong1988 , may I know what is your original purpose?

**Comment by YangYunLong1988** [comment]
Hi jiewen,
So Thanks for your information, my original purpose it to try some secure releated cmd, but now our POR will not support secure seeesion,   it will be better if the doc add some denpendency statement when use emu cmd.

**Comment by jyao1** [comment]
> add some denpendency statement when use emu cmd.

This is one way.

The other way is to override user setting. For example: https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_requester_emu/spdm_requester_spdm.c#L359C1-L396

**Comment by YangYunLong1988** [comment]
Owner have clarify the use case and solution.
