### ISSUE TITLE
Issue with Release folder creation on Windows environment.

### ISSUE THREAD

**Issue by Dhruva21** [DMTF/spdm-emu#297]
I built the spdm-emu code on windows environment. Used cmake to select the target as Debug or Release.
Steps followed for the build process:
1. mkdir build
2. cd build
3. **cmake -DARCH=x64 -DTOOLCHAIN=CLANG -DTARGET=<Debug|Release> -DCRYPTO=mbedtls ..**
4. msbuild spdm_emu.sln (added visual studio path to environment variable)

In step no.3, when I selected target as Debug mode,  Debug folder is created and all the executables are generated successfully. But I found the issue when the target is selected as Release. Even though the target is Release, Debug folder is generated.

For temporary workaround, I made modifications in the top level cmake file. I removed debug libraries that are set.

**Comment by jyao1** [comment]
@Dhruva21 , could you help do some analysis and fix the issue?

**Comment by Dhruva21** [comment]
@jyao1, after some analysis and study I figured out in the step 4 of the build process I was following, by default msbuild.exe generates the debug folder. So I had to additionally pass the property flag inorder to generate Release folder.
4. for debug folder: **msbuild spdm_emu.sln**
4. for release folder: **msbuild spdm_emu.sln /property:Configuration=Release**
Anyhow, I observed the debug libraries is included irrespective of the build type.
![image](https://github.com/DMTF/spdm-emu/assets/54857981/b8c0584b-c7bd-44e8-a013-0f62a0b482f2)

So I modified the cmake_c_standard_libraries based on cmake_build_type.
![image](https://github.com/DMTF/spdm-emu/assets/54857981/67657b78-05a6-41f0-8130-0c56bbccd196)
Can you review this change?
