### ISSUE TITLE
Error when running ./spdm_responder_emu --cap CERT,MEAS_NO_SIG,CHAL on SPDM_NEGOTIATE_ALGORITHMS

### ISSUE THREAD

**Issue by chedvadouer** [DMTF/spdm-emu#314]
I'm running spdm_responder_emu and ./spdm_responder_emu --cap CERT,MEAS_NO_SIG,CHAL
and getting this error:  (logs are attached)

SpdmReceiveRequest[0] msg SPDM_NEGOTIATE_ALGORITHMS(0xe3), size (0x30): 
0000: 13 e3 04 00 30 00 01 02 90 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 
0020: 02 20 1b 00 03 20 06 00 04 20 0f 00 05 20 01 00 
SpdmSendResponse[0] ...
SpdmSendResponse[0]: msg SPDM_ERROR(0x7f), size (0x4): 
0000: 13 7f 01 00 
[req_meas_chal_cert.log](https://github.com/DMTF/spdm-emu/files/13629005/req_meas_chal_cert.log)
[res_meas_chal_cert.log](https://github.com/DMTF/spdm-emu/files/13629006/res_meas_chal_cert.log)

**Comment by jyao1** [comment]
Issue 1: https://github.com/DMTF/libspdm/issues/2474
