### ISSUE TITLE
Need add support for LIBSPDM_ENABLE_VENDOR_DEFINED_MESSAGES

### ISSUE THREAD

**Issue by jyao1** [DMTF/spdm-emu#328]
See https://github.com/DMTF/libspdm/pull/2429

Without enabling, it will fail on IDE_KM test.

**Comment by jyao1** [comment]
@uvinrg, would you please submit a patch to enable spdm-emu?

**Comment by jyao1** [comment]
just run both spdm-emu, please.

**Comment by jyao1** [comment]
@Wenxing-hou , please investigate why CI did not catch this issue

**Comment by Wenxing-hou** [comment]
> @Wenxing-hou , please investigate why CI did not catch this issue

Hi all. I have investigated the SPDM-emu.  **The current spdm-emu doesn't  call the `libspdm_try_vendor_send_request_receive_response`  and `libspdm_get_vendor_defined_response`.**

The reason is:
When I added the dead loop in the submodule libspdm, such as:
```
libspdm_return_t libspdm_try_vendor_send_request_receive_response(
    libspdm_context_t *spdm_context,
    ...
    void *resp_data)
{
....
while(1);
```

```
libspdm_return_t libspdm_get_vendor_defined_response(libspdm_context_t *spdm_context,
                                                     size_t request_size,
                                                     const void *request,
                                                     size_t *response_size,
                                                     void *response)
{
...
while(1);
```
The spdm-emu run successfully without stop.

**Comment by jyao1** [comment]
@Wenxing-hou , why it does not call?

**Comment by uvinrg** [comment]
@jyao1 Running spdm_responder_emu and spdm_requester_emu without parameters works, though at some point responder return ERRRO 0xFE after a few messages.
I have created pull request https://github.com/DMTF/libspdm/pull/2533 to fix Libspdm vendor commands backwards-compatibility with existing code. It should fix the problem.
