### ISSUE TITLE
build failed: warning C4702: unreachable code  is treated as an error

### ISSUE THREAD

**Issue by qizhangz** [DMTF/spdm-emu#46]
[ 80%] Building C object out/spdm_common_lib.out/CMakeFiles/spdm_common_lib.dir/libspdm_com_opaque_data.c.obj
libspdm_com_opaque_data.c
C:\Workspace\project\mine\spdm-emu\libspdm\library\spdm_common_lib\libspdm_com_opaque_data.c(396) : error C2220: the following warning is treated as an error
C:\Workspace\project\mine\spdm-emu\libspdm\library\spdm_common_lib\libspdm_com_opaque_data.c(396) : warning C4702: unreachable code
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by qizhangz** [comment]
I will check this

**Comment by jyao1** [comment]
Why not just remove the unreachable code?

**Comment by jyao1** [comment]
See: https://github.com/DMTF/libspdm/issues/529
