### ISSUE TITLE
Can spdm-emu requester work with different responder (not exactly same spdm-emu responder) ?

### ISSUE THREAD

**Issue by manishc88** [DMTF/spdm-emu#69]
Hi,

We are planning to implement our own responder lib (it will not be exact same libspdm but with quite of modifications as per our device implementation) which will be hooked up to spdm-emu responder. But spdm-emu requester would still be the same using vanilla libspdm beneath. 

Is it some feasible approach ? Or there are some hidden considerations that the way spdm-emu requester and responder designed to work with only same vanilla libspdm ?

Thanks,
Manish

**Comment by steven-bellock** [comment]
>Is it some feasible approach ?

It is. It seems like the bulk of SPDM development is in Responder devices, and folks are using the spdm-emu Requester to test them out.

>Or there are some hidden considerations that the way spdm-emu requester and responder designed to work with only same vanilla libspdm ?

Hopefully not and if so that would signal a bug in libspdm or the SPDM specification.

**Comment by jyao1** [comment]
Right. It is feasible, as long as you follow the library header file definition.
There is no hidden assumption. If you find, you may file an issue.

**Comment by jyao1** [comment]
Question answered. Close.
