### ISSUE TITLE
Potential unalignment access in libspdm_get_response_challenge_auth()

### ISSUE THREAD

**Issue by lsun100** [DMTF/spdm-emu#70]
In libspdm_get_response_challenge_auth(), It seems that the code below might potentially cause unaligned access on certain CPUs.

 *(uint16_t *)ptr = (uint16_t)spdm_context->local_context
                    .opaque_challenge_auth_rsp_size;

Not sure if there's any alignment assumption of the 'ptr' at this location by design.

**Comment by steven-bellock** [comment]
Yes currently the implementation assumes little-endianness and unaligned accesses. See

https://github.com/DMTF/libspdm/issues/195
https://github.com/DMTF/libspdm/issues/276

We have been delaying this support in favor of other features until someone actually needs it. One of the issues is that Github CI doesn't support these natively so they would have to be emulated for testing.

**Comment by steven-bellock** [comment]
The main issues are in the libspdm repository as shown above.
