### ISSUE TITLE
SPDM_DATA_PEER_PUBLIC_ROOT_CERT’ undeclared

### ISSUE THREAD

**Issue by savatagecriss** [DMTF/spdm-emu#9]
Hi 
At first, thanks a lot for this open project spdm-emu, this give me a good topic to study SPDM spec.

And recently I try to build spdm-emu for ARM_GCC,
my code is clone from "8b193c1 revision",  and after run "cmake -DARCH=arm =DTOOLCHAIN=ARM_GCC -DARGET=Debug -DCRYPTO=openssl .."

I found a error as following, could you check this? thank you.
`_spdm-emu/spdm_emu/spdm_requester_emu/spdm_requester.c:268:11: error: ‘SPDM_DATA_PEER_PUBLIC_ROOT_CERT’ undeclared (first use in this function); did you mean ‘SPDM_DATA_PEER_PUBLIC_ROOT_CERT_HASH’?
  268 |           SPDM_DATA_PEER_PUBLIC_ROOT_CERT,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |           SPDM_DATA_PEER_PUBLIC_ROOT_CERT_HASH_`

John

**Comment by jyao1** [comment]
It seems the libspdm git submodule is not updated to latest one.

**Comment by jyao1** [comment]
can you try again?

**Comment by savatagecriss** [comment]
Hi jyao1, thanks, this version could be built
