### ISSUE TITLE
Questions about spdm_authentication()

### ISSUE THREAD

**Issue by rw8896** [DMTF/spdm-emu#99]
https://github.com/DMTF/spdm-emu/blob/fca95c2de76720e5c8085966bc77fcab1f8604a7/spdm_emu/spdm_requester_emu/spdm_requester_authentication.c#L84-L108

Hi,

I am not pretty sure but these lines seem to verify the recent changes of allowing GET_DIGESTS/GET_CERTIFICATE after CHALLENGE.
Would you help take them out if they are not supposed to be part of a typical authentication procedure?

Thanks!

**Comment by jyao1** [comment]
This is example to cover some case that digest get after authenticate. I dont think we should take them out.
